target: ./_site
deploy_target: ./_site_deploy
deploy_target_compress: ./site.tar.gz
source: ./website
host: henrylawson.net
wwwuser: www-hln
publish: /srv/www/henrylawson.net
upload_temp: /tmp
publish_temp: /tmp/henrylawson.net
link_checker_log: linkchecker.log
default_host: 0.0.0.0
default_port: 4000
posts: ./website/_posts
