source 'https://rubygems.org'

gem 'jekyll'
gem 'rake'
gem 'jekyll-assets'
gem 'sprockets-sass'
gem 'sprockets-helpers'
gem 'sass'
gem 'uglifier'
gem 'jekyll-sitemap'
gem 'redcarpet'
gem 'pygments.rb'
gem 'nokogiri'
gem 'fastimage'
