name: Henry Lawson
markdown: redcarpet
highlighter: pygments
permalink: /:title
front_post_count: 2
recent_article_count: 10
excerpt_separator: <!--more-->
hostname: https://henrylawson.net
exclude: ["*.bak", "*.swp"]
meta:
  image: https://henrylawson.net/images/henry_lawson.jpg
  description: A repository of articles about software development, management and delivery. Sometimes thoughtful, somtimes random - hopefully informative and insightful.
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  cache: false
  js_compressor:  uglifier
  css_compressor: sass
gems:
    - jekyll-sitemap
