name: Henry Lawson
alternativeName: HenryLawson.net
markdown: redcarpet
highlighter: pygments
permalink: /:title
front_post_count: 3
recent_article_count: 10
excerpt_separator: <!--more-->
url: https://henrylawson.net
exclude: ["*.bak", "*.swp"]
meta:
  image: henry_lawson_bw.jpg
  title: Henry Lawson | A Blog on Software and Business Management
  description: Henry Lawson - Software Consultant, Developer and Business Management enthusiast. A repository of articles and blog posts that cover Agile Principles and Practices, Software Delivery, Programming Languages (C#, Ruby, Java, JavaScript, Python and Clojure). The articles posted here aim to be great references of thoughtful, sometimes random but hopefully informative and insightful information.
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  cache: false
  js_compressor:  uglifier
  css_compressor: sass
gems:
    - jekyll-sitemap
