name: Henry Lawson
markdown: redcarpet
highlighter: pygments
permalink: /:title/
front_post_count: 2
recent_article_count: 10
excerpt_separator: <!--more-->
assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
