name: Henry Lawson
markdown: redcarpet
highlighter: pygments
permalink: /:title
front_post_count: 2
recent_article_count: 10
excerpt_separator: <!--more-->
url: https://henrylawson.net
exclude: ["*.bak", "*.swp"]
meta:
  image: https://henrylawson.net/images/henry_lawson.jpg
  title: Henry Lawson's Blog on Software Development and Business Management
  description: The home and blog of Software Consultant, Developer and Business Management enthusiast, Henry Lawson. A repository of articles and blog posts that cover Agile Principles, Agile Practices, Software Development, Business Management and Software Delivery. The articles posted here aim to be great references of thoughtful, sometimes random but hopefully informative, valuable and insightful information.
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  cache: false
  js_compressor:  uglifier
  css_compressor: sass
gems:
    - jekyll-sitemap
