name: Henry Lawson
markdown: redcarpet
highlighter: pygments
permalink: /:title
front_post_count: 2
recent_article_count: 10
excerpt_separator: <!--more-->
hostname: https://henrylawson.net
url: https://henrylawson.net
exclude: ["*.bak", "*.swp"]
meta:
  image: https://henrylawson.net/images/henry_lawson.jpg
  description: The home and blog of Software Consultant, Developer and Business Management enthusiast, Henry Lawson. This site serves as a repository of articles of my learnings and insights about Software Development, Business Management and Software Delivery. Sometimes thoughtful, sometimes random - hopefully informative and insightful.
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  cache: false
  js_compressor:  uglifier
  css_compressor: sass
gems:
    - jekyll-sitemap
